# generated by datamodel-codegen:
#   filename:  info.json
#   timestamp: 2022-07-29T12:06:17+00:00

import uuid
from typing import List, Any, Optional
from pydantic import BaseModel, Field


class MongoBaseModel(BaseModel):
    id: str = Field(
        default_factory=uuid.uuid4,
        alias="_id",
        examples=[
            "NA1_4387530978-wgvrKfcuCGDmgyrUmiXknS41acg6Y26hfQwsXNj_eJ86Tv8_Bb7SBOUVSQqI1JdyBSmq92XGDrGYHA"
        ],
    )


class Metadata(BaseModel):
    data_version: str = Field(..., examples=["5"], title="The data_version Schema")
    match_id: str = Field(..., examples=["NA1_4356726048"], title="The match_id Schema")
    participants: List[str] = Field(
        ...,
        examples=[
            [
                "OnW1Dw_JX8vapRJEb-ZVjqdKVknpD2IGd6ZWowLTrkmoEeqZlGZTx6iR5yVW6a5tu5JVwEeDl5pToA",
                "St_wL0UOxf_11zObuZn-7FE-yGRGjfjFaeHlAbCMCESgyqgS636iSJhu5qxxDqBq7XuNlL4I161r8g",
                "gknC54sLodRm73oByx1NIFCSfm54xwWHjpKHygy5vOQsTqpu_xtnffa_mmgUncFExF3vfvenX6HXBw",
                "SIxmDzDxdLvM02pCXLiUI86YYgmqCozEeXBst7wGjAfen4M4kHnWfUPWQyhEb17Bmgc4UUSEnhtu5g",
                "FjLKIVYYUSrV37F_ZcBfkdPfRtkqXlYgw5u8WWv6WI7MYX1Jied9NPYPNLYum1ukzbYyWcCCZDMCKw",
                "TKiOPQ-2gmZ2BJEKRyRSRQneWiJHgoG-VwTpDSSvnTdpQdLkljmB9wxxucxx1TrxheBsAhAxlgqAJw",
                "l1I1H2cDsK118VC-ZvKzZqJ5QZynz7aJ7GsMR3fu5KNbmK3a0FTNivKnzyHZY7mq9QFWVmPpaq6QdA",
                "SYeHG18d6HblklTVFAcDoGsAXWwTq1ZeflhRbaztiP900sTmW7qH8XNeyZyciYbeZe1daqEK7Lt_TQ",
            ]
        ],
        title="The participants Schema",
    )


class Companion(BaseModel):
    content_ID: str = Field(
        ...,
        examples=["023144c0-80e7-445e-846e-82b0883b9ada"],
        title="The content_ID Schema",
    )
    skin_ID: int = Field(..., examples=[33], title="The skin_ID Schema")
    species: str = Field(..., examples=["PetDowsie"], title="The species Schema")


class Trait(BaseModel):
    name: str = Field(..., examples=["Set7_Cavalier"], title="The name Schema")
    num_units: int = Field(..., examples=[1], title="The num_units Schema")
    style: int = Field(..., examples=[0], title="The style Schema")
    tier_current: int = Field(..., examples=[0], title="The tier_current Schema")
    tier_total: int = Field(..., examples=[4], title="The tier_total Schema")


class Unit(BaseModel):
    character_id: str = Field(
        ..., examples=["TFT7_Swain"], title="The character_id Schema"
    )
    itemNames: List[str] = Field(
        ...,
        examples=[
            ["TFT_Item_StatikkShiv", "TFT_Item_Quicksilver", "TFT_Item_ArchangelsStaff"]
        ],
        title="The itemNames Schema",
    )
    items: List[int] = Field(..., examples=[[24, 69, 34]], title="The items Schema")
    name: str = Field(..., examples=[""], title="The name Schema")
    rarity: int = Field(..., examples=[2], title="The rarity Schema")
    tier: int = Field(..., examples=[2], title="The tier Schema")


class Participant(BaseModel):
    augments: List[str] = Field(
        ...,
        examples=[
            [
                "TFT7_Augment_AxiomArc1",
                "TFT6_Augment_SecondWind1",
                "TFT7_Augment_DragonmancerInspire",
            ]
        ],
        title="The augments Schema",
    )
    companion: Companion = Field(
        ...,
        examples=[
            {
                "content_ID": "023144c0-80e7-445e-846e-82b0883b9ada",
                "skin_ID": 33,
                "species": "PetDowsie",
            }
        ],
        title="The companion Schema",
    )
    gold_left: int = Field(..., examples=[1], title="The gold_left Schema")
    last_round: int = Field(..., examples=[30], title="The last_round Schema")
    level: int = Field(..., examples=[8], title="The level Schema")
    placement: int = Field(..., examples=[6], title="The placement Schema")
    players_eliminated: int = Field(
        ..., examples=[0], title="The players_eliminated Schema"
    )
    puuid: str = Field(
        ...,
        examples=[
            "OnW1Dw_JX8vapRJEb-ZVjqdKVknpD2IGd6ZWowLTrkmoEeqZlGZTx6iR5yVW6a5tu5JVwEeDl5pToA"
        ],
        title="The puuid Schema",
    )
    time_eliminated: float = Field(
        ..., examples=[1806.2384033203125], title="The time_eliminated Schema"
    )
    total_damage_to_players: int = Field(
        ..., examples=[66], title="The total_damage_to_players Schema"
    )
    traits: List[Trait] = Field(
        ...,
        examples=[
            [
                {
                    "name": "Set7_Cavalier",
                    "num_units": 1,
                    "style": 0,
                    "tier_current": 0,
                    "tier_total": 4,
                }
            ]
        ],
        title="The traits Schema",
    )
    units: List[Unit] = Field(
        ...,
        examples=[
            [
                {
                    "character_id": "TFT7_Swain",
                    "itemNames": [
                        "TFT_Item_StatikkShiv",
                        "TFT_Item_Quicksilver",
                        "TFT_Item_ArchangelsStaff",
                    ],
                    "items": [24, 69, 34],
                    "name": "",
                    "rarity": 2,
                    "tier": 2,
                }
            ]
        ],
        title="The units Schema",
    )


class Info(BaseModel):
    game_datetime: int = Field(
        ..., examples=[1656394119211], title="The game_datetime Schema"
    )
    game_length: float = Field(
        ..., examples=[2371.135986328125], title="The game_length Schema"
    )
    game_version: str = Field(
        ...,
        examples=[
            "Version 12.12.450.4196 (Jun 24 2022/13: 37: 31) [PUBLIC    ] <Releases/12.12>"
        ],
        title="The game_version Schema",
    )
    participants: List[Participant] = Field(
        ...,
        examples=[
            [
                {
                    "augments": [
                        "TFT7_Augment_AxiomArc1",
                        "TFT6_Augment_SecondWind1",
                        "TFT7_Augment_DragonmancerInspire",
                    ],
                    "companion": {
                        "content_ID": "023144c0-80e7-445e-846e-82b0883b9ada",
                        "skin_ID": 33,
                        "species": "PetDowsie",
                    },
                    "gold_left": 1,
                    "last_round": 30,
                    "level": 8,
                    "placement": 6,
                    "players_eliminated": 0,
                    "puuid": "OnW1Dw_JX8vapRJEb-ZVjqdKVknpD2IGd6ZWowLTrkmoEeqZlGZTx6iR5yVW6a5tu5JVwEeDl5pToA",
                    "time_eliminated": 1806.2384033203125,
                    "total_damage_to_players": 66,
                    "traits": [
                        {
                            "name": "Set7_Cavalier",
                            "num_units": 1,
                            "style": 0,
                            "tier_current": 0,
                            "tier_total": 4,
                        }
                    ],
                    "units": [
                        {
                            "character_id": "TFT7_Swain",
                            "itemNames": [
                                "TFT_Item_StatikkShiv",
                                "TFT_Item_Quicksilver",
                                "TFT_Item_ArchangelsStaff",
                            ],
                            "items": [24, 69, 34],
                            "name": "",
                            "rarity": 2,
                            "tier": 2,
                        }
                    ],
                }
            ]
        ],
        title="The participants Schema",
    )
    queue_id: int = Field(..., examples=[1100], title="The queue_id Schema")
    tft_game_type: str = Field(
        ..., examples=["standard"], title="The tft_game_type Schema"
    )
    tft_set_core_name: str = Field(
        ..., examples=["TFTSet7"], title="The tft_set_core_name Schema"
    )
    tft_set_number: int = Field(..., examples=[7], title="The tft_set_number Schema")


class MatchDetail(MongoBaseModel):
    # id: str = Field(default_factory=uuid.uuid4, alias="_id", examples=[
    #                 'NA1_4387530978-wgvrKfcuCGDmgyrUmiXknS41acg6Y26hfQwsXNj_eJ86Tv8_Bb7SBOUVSQqI1JdyBSmq92XGDrGYHA'])
    metadata: Metadata = Field(
        ...,
        examples=[
            {
                "data_version": "5",
                "match_id": "NA1_4356726048",
                "participants": [
                    "OnW1Dw_JX8vapRJEb-ZVjqdKVknpD2IGd6ZWowLTrkmoEeqZlGZTx6iR5yVW6a5tu5JVwEeDl5pToA",
                    "St_wL0UOxf_11zObuZn-7FE-yGRGjfjFaeHlAbCMCESgyqgS636iSJhu5qxxDqBq7XuNlL4I161r8g",
                    "gknC54sLodRm73oByx1NIFCSfm54xwWHjpKHygy5vOQsTqpu_xtnffa_mmgUncFExF3vfvenX6HXBw",
                    "SIxmDzDxdLvM02pCXLiUI86YYgmqCozEeXBst7wGjAfen4M4kHnWfUPWQyhEb17Bmgc4UUSEnhtu5g",
                    "FjLKIVYYUSrV37F_ZcBfkdPfRtkqXlYgw5u8WWv6WI7MYX1Jied9NPYPNLYum1ukzbYyWcCCZDMCKw",
                    "TKiOPQ-2gmZ2BJEKRyRSRQneWiJHgoG-VwTpDSSvnTdpQdLkljmB9wxxucxx1TrxheBsAhAxlgqAJw",
                    "l1I1H2cDsK118VC-ZvKzZqJ5QZynz7aJ7GsMR3fu5KNbmK3a0FTNivKnzyHZY7mq9QFWVmPpaq6QdA",
                    "SYeHG18d6HblklTVFAcDoGsAXWwTq1ZeflhRbaztiP900sTmW7qH8XNeyZyciYbeZe1daqEK7Lt_TQ",
                ],
            }
        ],
        title="The metadata Schema",
    )
    info: Info = Field(
        ...,
        examples=[
            {
                "game_datetime": 1656394119211,
                "game_length": 2371.135986328125,
                "game_version": "Version 12.12.450.4196 (Jun 24 2022/13: 37: 31) [PUBLIC    ] <Releases/12.12>",
                "participants": [
                    {
                        "augments": [
                            "TFT7_Augment_AxiomArc1",
                            "TFT6_Augment_SecondWind1",
                            "TFT7_Augment_DragonmancerInspire",
                        ],
                        "companion": {
                            "content_ID": "023144c0-80e7-445e-846e-82b0883b9ada",
                            "skin_ID": 33,
                            "species": "PetDowsie",
                        },
                        "gold_left": 1,
                        "last_round": 30,
                        "level": 8,
                        "placement": 6,
                        "players_eliminated": 0,
                        "puuid": "OnW1Dw_JX8vapRJEb-ZVjqdKVknpD2IGd6ZWowLTrkmoEeqZlGZTx6iR5yVW6a5tu5JVwEeDl5pToA",
                        "time_eliminated": 1806.2384033203125,
                        "total_damage_to_players": 66,
                        "traits": [
                            {
                                "name": "Set7_Cavalier",
                                "num_units": 1,
                                "style": 0,
                                "tier_current": 0,
                                "tier_total": 4,
                            }
                        ],
                        "units": [
                            {
                                "character_id": "TFT7_Swain",
                                "itemNames": [
                                    "TFT_Item_StatikkShiv",
                                    "TFT_Item_Quicksilver",
                                    "TFT_Item_ArchangelsStaff",
                                ],
                                "items": [24, 69, 34],
                                "name": "",
                                "rarity": 2,
                                "tier": 2,
                            }
                        ],
                    }
                ],
                "queue_id": 1100,
                "tft_game_type": "standard",
                "tft_set_core_name": "TFTSet7",
                "tft_set_number": 7,
            }
        ],
        title="The info Schema",
    )


class MatchDetailUpdate(BaseModel):
    metadata: Metadata = Field(
        ...,
        examples=[
            {
                "data_version": "5",
                "match_id": "NA1_4356726048",
                "participants": [
                    "OnW1Dw_JX8vapRJEb-ZVjqdKVknpD2IGd6ZWowLTrkmoEeqZlGZTx6iR5yVW6a5tu5JVwEeDl5pToA",
                    "St_wL0UOxf_11zObuZn-7FE-yGRGjfjFaeHlAbCMCESgyqgS636iSJhu5qxxDqBq7XuNlL4I161r8g",
                    "gknC54sLodRm73oByx1NIFCSfm54xwWHjpKHygy5vOQsTqpu_xtnffa_mmgUncFExF3vfvenX6HXBw",
                    "SIxmDzDxdLvM02pCXLiUI86YYgmqCozEeXBst7wGjAfen4M4kHnWfUPWQyhEb17Bmgc4UUSEnhtu5g",
                    "FjLKIVYYUSrV37F_ZcBfkdPfRtkqXlYgw5u8WWv6WI7MYX1Jied9NPYPNLYum1ukzbYyWcCCZDMCKw",
                    "TKiOPQ-2gmZ2BJEKRyRSRQneWiJHgoG-VwTpDSSvnTdpQdLkljmB9wxxucxx1TrxheBsAhAxlgqAJw",
                    "l1I1H2cDsK118VC-ZvKzZqJ5QZynz7aJ7GsMR3fu5KNbmK3a0FTNivKnzyHZY7mq9QFWVmPpaq6QdA",
                    "SYeHG18d6HblklTVFAcDoGsAXWwTq1ZeflhRbaztiP900sTmW7qH8XNeyZyciYbeZe1daqEK7Lt_TQ",
                ],
            }
        ],
        title="The metadata Schema",
    )
    info: Info = Field(
        ...,
        examples=[
            {
                "game_datetime": 1656394119211,
                "game_length": 2371.135986328125,
                "game_version": "Version 12.12.450.4196 (Jun 24 2022/13: 37: 31) [PUBLIC    ] <Releases/12.12>",
                "participants": [
                    {
                        "augments": [
                            "TFT7_Augment_AxiomArc1",
                            "TFT6_Augment_SecondWind1",
                            "TFT7_Augment_DragonmancerInspire",
                        ],
                        "companion": {
                            "content_ID": "023144c0-80e7-445e-846e-82b0883b9ada",
                            "skin_ID": 33,
                            "species": "PetDowsie",
                        },
                        "gold_left": 1,
                        "last_round": 30,
                        "level": 8,
                        "placement": 6,
                        "players_eliminated": 0,
                        "puuid": "OnW1Dw_JX8vapRJEb-ZVjqdKVknpD2IGd6ZWowLTrkmoEeqZlGZTx6iR5yVW6a5tu5JVwEeDl5pToA",
                        "time_eliminated": 1806.2384033203125,
                        "total_damage_to_players": 66,
                        "traits": [
                            {
                                "name": "Set7_Cavalier",
                                "num_units": 1,
                                "style": 0,
                                "tier_current": 0,
                                "tier_total": 4,
                            }
                        ],
                        "units": [
                            {
                                "character_id": "TFT7_Swain",
                                "itemNames": [
                                    "TFT_Item_StatikkShiv",
                                    "TFT_Item_Quicksilver",
                                    "TFT_Item_ArchangelsStaff",
                                ],
                                "items": [24, 69, 34],
                                "name": "",
                                "rarity": 2,
                                "tier": 2,
                            }
                        ],
                    }
                ],
                "queue_id": 1100,
                "tft_game_type": "standard",
                "tft_set_core_name": "TFTSet7",
                "tft_set_number": 7,
            }
        ],
        title="The info Schema",
    )
