version: '3.8'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
            
        command: "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
        container_name: tftchamp_endpoint
        ports:
            - "${PORT:-8000}:${PORT:-8000}"