# generated by datamodel-codegen:
#   filename:  match_schema.json
#   timestamp: 2022-07-30T09:14:24+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field


class RootSchema(BaseModel):
    placement: int = Field(..., examples=[8], title='The placement Schema')
    match_id: str = Field(..., examples=['NA1_4387530978'], title='The match_id Schema')
    augment0: str = Field(
        ..., examples=['TFT6_Augment_BlueBattery2'], title='The augment0 Schema'
    )
    augment1: str = Field(
        ..., examples=['TFT6_Augment_TinyTitans'], title='The augment1 Schema'
    )
    augment2: str = Field(
        ..., examples=['TFT7_Augment_UrfsGrabBag1'], title='The augment2 Schema'
    )
    Set7_Assassin: float = Field(..., examples=[2.0], title='The Set7_Assassin Schema')
    Set7_Astral: Any = Field(..., examples=[None], title='The Set7_Astral Schema')
    Set7_Bard: Any = Field(..., examples=[None], title='The Set7_Bard Schema')
    Set7_Bruiser: float = Field(..., examples=[1.0], title='The Set7_Bruiser Schema')
    Set7_Cannoneer: Any = Field(..., examples=[None], title='The Set7_Cannoneer Schema')
    Set7_Cavalier: Any = Field(..., examples=[None], title='The Set7_Cavalier Schema')
    Set7_Dragon: float = Field(..., examples=[1.0], title='The Set7_Dragon Schema')
    Set7_Dragonmancer: Any = Field(
        ..., examples=[None], title='The Set7_Dragonmancer Schema'
    )
    Set7_Evoker: Any = Field(..., examples=[None], title='The Set7_Evoker Schema')
    Set7_Guardian: Any = Field(..., examples=[None], title='The Set7_Guardian Schema')
    Set7_Guild: float = Field(..., examples=[1.0], title='The Set7_Guild Schema')
    Set7_Jade: Any = Field(..., examples=[None], title='The Set7_Jade Schema')
    Set7_Legend: float = Field(..., examples=[0.0], title='The Set7_Legend Schema')
    Set7_Mage: float = Field(..., examples=[0.0], title='The Set7_Mage Schema')
    Set7_Mirage: Any = Field(..., examples=[None], title='The Set7_Mirage Schema')
    Set7_Mystic: Any = Field(..., examples=[None], title='The Set7_Mystic Schema')
    Set7_Ragewing: Any = Field(..., examples=[None], title='The Set7_Ragewing Schema')
    Set7_Revel: Any = Field(..., examples=[None], title='The Set7_Revel Schema')
    Set7_Scalescorn: float = Field(
        ..., examples=[0.0], title='The Set7_Scalescorn Schema'
    )
    Set7_Shapeshifter: float = Field(
        ..., examples=[0.0], title='The Set7_Shapeshifter Schema'
    )
    Set7_Shimmerscale: Any = Field(
        ..., examples=[None], title='The Set7_Shimmerscale Schema'
    )
    Set7_SpellThief: Any = Field(
        ..., examples=[None], title='The Set7_SpellThief Schema'
    )
    Set7_Starcaller: Any = Field(
        ..., examples=[None], title='The Set7_Starcaller Schema'
    )
    Set7_Swiftshot: Any = Field(..., examples=[None], title='The Set7_Swiftshot Schema')
    Set7_Tempest: float = Field(..., examples=[1.0], title='The Set7_Tempest Schema')
    Set7_Trainer: Any = Field(..., examples=[None], title='The Set7_Trainer Schema')
    Set7_Warrior: Any = Field(..., examples=[None], title='The Set7_Warrior Schema')
    Set7_Whispers: float = Field(..., examples=[3.0], title='The Set7_Whispers Schema')
    TFT7_Aatrox: Any = Field(..., examples=[None], title='The TFT7_Aatrox Schema')
    TFT7_Aatrox_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Aatrox_item0 Schema'
    )
    TFT7_Aatrox_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Aatrox_item1 Schema'
    )
    TFT7_Aatrox_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Aatrox_item2 Schema'
    )
    TFT7_Anivia: Any = Field(..., examples=[None], title='The TFT7_Anivia Schema')
    TFT7_Anivia_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Anivia_item0 Schema'
    )
    TFT7_Anivia_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Anivia_item1 Schema'
    )
    TFT7_Anivia_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Anivia_item2 Schema'
    )
    TFT7_AoShin: Any = Field(..., examples=[None], title='The TFT7_AoShin Schema')
    TFT7_AoShin_item0: Any = Field(
        ..., examples=[None], title='The TFT7_AoShin_item0 Schema'
    )
    TFT7_AoShin_item1: Any = Field(
        ..., examples=[None], title='The TFT7_AoShin_item1 Schema'
    )
    TFT7_AoShin_item2: Any = Field(
        ..., examples=[None], title='The TFT7_AoShin_item2 Schema'
    )
    TFT7_Ashe: Any = Field(..., examples=[None], title='The TFT7_Ashe Schema')
    TFT7_Ashe_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Ashe_item0 Schema'
    )
    TFT7_Ashe_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Ashe_item1 Schema'
    )
    TFT7_Ashe_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Ashe_item2 Schema'
    )
    TFT7_AurelionSol: Any = Field(
        ..., examples=[None], title='The TFT7_AurelionSol Schema'
    )
    TFT7_AurelionSol_item0: Any = Field(
        ..., examples=[None], title='The TFT7_AurelionSol_item0 Schema'
    )
    TFT7_AurelionSol_item1: Any = Field(
        ..., examples=[None], title='The TFT7_AurelionSol_item1 Schema'
    )
    TFT7_AurelionSol_item2: Any = Field(
        ..., examples=[None], title='The TFT7_AurelionSol_item2 Schema'
    )
    TFT7_Bard: Any = Field(..., examples=[None], title='The TFT7_Bard Schema')
    TFT7_Bard_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Bard_item0 Schema'
    )
    TFT7_Bard_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Bard_item1 Schema'
    )
    TFT7_Bard_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Bard_item2 Schema'
    )
    TFT7_Braum: Any = Field(..., examples=[None], title='The TFT7_Braum Schema')
    TFT7_Braum_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Braum_item0 Schema'
    )
    TFT7_Braum_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Braum_item1 Schema'
    )
    TFT7_Braum_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Braum_item2 Schema'
    )
    TFT7_Corki: Any = Field(..., examples=[None], title='The TFT7_Corki Schema')
    TFT7_Corki_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Corki_item0 Schema'
    )
    TFT7_Corki_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Corki_item1 Schema'
    )
    TFT7_Corki_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Corki_item2 Schema'
    )
    TFT7_Diana: float = Field(..., examples=[1.0], title='The TFT7_Diana Schema')
    TFT7_Diana_item0: str = Field(
        ..., examples=['ForceOfNature'], title='The TFT7_Diana_item0 Schema'
    )
    TFT7_Diana_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Diana_item1 Schema'
    )
    TFT7_Diana_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Diana_item2 Schema'
    )
    TFT7_DragonBlue: Any = Field(
        ..., examples=[None], title='The TFT7_DragonBlue Schema'
    )
    TFT7_DragonBlue_item0: Any = Field(
        ..., examples=[None], title='The TFT7_DragonBlue_item0 Schema'
    )
    TFT7_DragonBlue_item1: Any = Field(
        ..., examples=[None], title='The TFT7_DragonBlue_item1 Schema'
    )
    TFT7_DragonBlue_item2: Any = Field(
        ..., examples=[None], title='The TFT7_DragonBlue_item2 Schema'
    )
    TFT7_DragonGold: Any = Field(
        ..., examples=[None], title='The TFT7_DragonGold Schema'
    )
    TFT7_DragonGold_item0: Any = Field(
        ..., examples=[None], title='The TFT7_DragonGold_item0 Schema'
    )
    TFT7_DragonGold_item1: Any = Field(
        ..., examples=[None], title='The TFT7_DragonGold_item1 Schema'
    )
    TFT7_DragonGold_item2: Any = Field(
        ..., examples=[None], title='The TFT7_DragonGold_item2 Schema'
    )
    TFT7_DragonGreen: Any = Field(
        ..., examples=[None], title='The TFT7_DragonGreen Schema'
    )
    TFT7_DragonGreen_item0: Any = Field(
        ..., examples=[None], title='The TFT7_DragonGreen_item0 Schema'
    )
    TFT7_DragonGreen_item1: Any = Field(
        ..., examples=[None], title='The TFT7_DragonGreen_item1 Schema'
    )
    TFT7_DragonGreen_item2: Any = Field(
        ..., examples=[None], title='The TFT7_DragonGreen_item2 Schema'
    )
    TFT7_DragonPurple: float = Field(
        ..., examples=[2.0], title='The TFT7_DragonPurple Schema'
    )
    TFT7_DragonPurple_item0: str = Field(
        ..., examples=['InfinityEdge'], title='The TFT7_DragonPurple_item0 Schema'
    )
    TFT7_DragonPurple_item1: str = Field(
        ..., examples=['UnstableConcoction'], title='The TFT7_DragonPurple_item1 Schema'
    )
    TFT7_DragonPurple_item2: str = Field(
        ..., examples=['GuardianAngel'], title='The TFT7_DragonPurple_item2 Schema'
    )
    TFT7_Elise: float = Field(..., examples=[2.0], title='The TFT7_Elise Schema')
    TFT7_Elise_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Elise_item0 Schema'
    )
    TFT7_Elise_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Elise_item1 Schema'
    )
    TFT7_Elise_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Elise_item2 Schema'
    )
    TFT7_Ezreal: Any = Field(..., examples=[None], title='The TFT7_Ezreal Schema')
    TFT7_Ezreal_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Ezreal_item0 Schema'
    )
    TFT7_Ezreal_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Ezreal_item1 Schema'
    )
    TFT7_Ezreal_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Ezreal_item2 Schema'
    )
    TFT7_Gnar: Any = Field(..., examples=[None], title='The TFT7_Gnar Schema')
    TFT7_Gnar_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Gnar_item0 Schema'
    )
    TFT7_Gnar_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Gnar_item1 Schema'
    )
    TFT7_Gnar_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Gnar_item2 Schema'
    )
    TFT7_Hecarim: Any = Field(..., examples=[None], title='The TFT7_Hecarim Schema')
    TFT7_Hecarim_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Hecarim_item0 Schema'
    )
    TFT7_Hecarim_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Hecarim_item1 Schema'
    )
    TFT7_Hecarim_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Hecarim_item2 Schema'
    )
    TFT7_Heimerdinger: Any = Field(
        ..., examples=[None], title='The TFT7_Heimerdinger Schema'
    )
    TFT7_Heimerdinger_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Heimerdinger_item0 Schema'
    )
    TFT7_Heimerdinger_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Heimerdinger_item1 Schema'
    )
    TFT7_Heimerdinger_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Heimerdinger_item2 Schema'
    )
    TFT7_Illaoi: Any = Field(..., examples=[None], title='The TFT7_Illaoi Schema')
    TFT7_Illaoi_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Illaoi_item0 Schema'
    )
    TFT7_Illaoi_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Illaoi_item1 Schema'
    )
    TFT7_Illaoi_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Illaoi_item2 Schema'
    )
    TFT7_Jinx: Any = Field(..., examples=[None], title='The TFT7_Jinx Schema')
    TFT7_Jinx_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Jinx_item0 Schema'
    )
    TFT7_Jinx_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Jinx_item1 Schema'
    )
    TFT7_Jinx_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Jinx_item2 Schema'
    )
    TFT7_Karma: Any = Field(..., examples=[None], title='The TFT7_Karma Schema')
    TFT7_Karma_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Karma_item0 Schema'
    )
    TFT7_Karma_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Karma_item1 Schema'
    )
    TFT7_Karma_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Karma_item2 Schema'
    )
    TFT7_Kayn: Any = Field(..., examples=[None], title='The TFT7_Kayn Schema')
    TFT7_Kayn_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Kayn_item0 Schema'
    )
    TFT7_Kayn_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Kayn_item1 Schema'
    )
    TFT7_Kayn_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Kayn_item2 Schema'
    )
    TFT7_LeeSin: Any = Field(..., examples=[None], title='The TFT7_LeeSin Schema')
    TFT7_LeeSin_item0: Any = Field(
        ..., examples=[None], title='The TFT7_LeeSin_item0 Schema'
    )
    TFT7_LeeSin_item1: Any = Field(
        ..., examples=[None], title='The TFT7_LeeSin_item1 Schema'
    )
    TFT7_LeeSin_item2: Any = Field(
        ..., examples=[None], title='The TFT7_LeeSin_item2 Schema'
    )
    TFT7_Leona: Any = Field(..., examples=[None], title='The TFT7_Leona Schema')
    TFT7_Leona_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Leona_item0 Schema'
    )
    TFT7_Leona_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Leona_item1 Schema'
    )
    TFT7_Leona_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Leona_item2 Schema'
    )
    TFT7_Lillia: Any = Field(..., examples=[None], title='The TFT7_Lillia Schema')
    TFT7_Lillia_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Lillia_item0 Schema'
    )
    TFT7_Lillia_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Lillia_item1 Schema'
    )
    TFT7_Lillia_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Lillia_item2 Schema'
    )
    TFT7_Lulu: Any = Field(..., examples=[None], title='The TFT7_Lulu Schema')
    TFT7_Lulu_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Lulu_item0 Schema'
    )
    TFT7_Lulu_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Lulu_item1 Schema'
    )
    TFT7_Lulu_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Lulu_item2 Schema'
    )
    TFT7_Nami: Any = Field(..., examples=[None], title='The TFT7_Nami Schema')
    TFT7_Nami_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Nami_item0 Schema'
    )
    TFT7_Nami_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Nami_item1 Schema'
    )
    TFT7_Nami_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Nami_item2 Schema'
    )
    TFT7_Neeko: Any = Field(..., examples=[None], title='The TFT7_Neeko Schema')
    TFT7_Neeko_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Neeko_item0 Schema'
    )
    TFT7_Neeko_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Neeko_item1 Schema'
    )
    TFT7_Neeko_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Neeko_item2 Schema'
    )
    TFT7_Nidalee: Any = Field(..., examples=[None], title='The TFT7_Nidalee Schema')
    TFT7_Nidalee_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Nidalee_item0 Schema'
    )
    TFT7_Nidalee_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Nidalee_item1 Schema'
    )
    TFT7_Nidalee_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Nidalee_item2 Schema'
    )
    TFT7_Nunu: Any = Field(..., examples=[None], title='The TFT7_Nunu Schema')
    TFT7_Nunu_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Nunu_item0 Schema'
    )
    TFT7_Nunu_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Nunu_item1 Schema'
    )
    TFT7_Nunu_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Nunu_item2 Schema'
    )
    TFT7_Olaf: Any = Field(..., examples=[None], title='The TFT7_Olaf Schema')
    TFT7_Olaf_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Olaf_item0 Schema'
    )
    TFT7_Olaf_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Olaf_item1 Schema'
    )
    TFT7_Olaf_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Olaf_item2 Schema'
    )
    TFT7_Ornn: float = Field(..., examples=[1.0], title='The TFT7_Ornn Schema')
    TFT7_Ornn_item0: str = Field(
        ..., examples=['Morellonomicon'], title='The TFT7_Ornn_item0 Schema'
    )
    TFT7_Ornn_item1: str = Field(
        ..., examples=['GargoyleStoneplate'], title='The TFT7_Ornn_item1 Schema'
    )
    TFT7_Ornn_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Ornn_item2 Schema'
    )
    TFT7_Pyke: float = Field(..., examples=[1.0], title='The TFT7_Pyke Schema')
    TFT7_Pyke_item0: str = Field(
        ..., examples=['Zephyr'], title='The TFT7_Pyke_item0 Schema'
    )
    TFT7_Pyke_item1: str = Field(
        ..., examples=['InfinityEdge'], title='The TFT7_Pyke_item1 Schema'
    )
    TFT7_Pyke_item2: str = Field(
        ..., examples=['FrozenHeart'], title='The TFT7_Pyke_item2 Schema'
    )
    TFT7_Qiyana: float = Field(..., examples=[1.0], title='The TFT7_Qiyana Schema')
    TFT7_Qiyana_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Qiyana_item0 Schema'
    )
    TFT7_Qiyana_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Qiyana_item1 Schema'
    )
    TFT7_Qiyana_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Qiyana_item2 Schema'
    )
    TFT7_Ryze: Any = Field(..., examples=[None], title='The TFT7_Ryze Schema')
    TFT7_Ryze_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Ryze_item0 Schema'
    )
    TFT7_Ryze_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Ryze_item1 Schema'
    )
    TFT7_Ryze_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Ryze_item2 Schema'
    )
    TFT7_Sejuani: Any = Field(..., examples=[None], title='The TFT7_Sejuani Schema')
    TFT7_Sejuani_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Sejuani_item0 Schema'
    )
    TFT7_Sejuani_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Sejuani_item1 Schema'
    )
    TFT7_Sejuani_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Sejuani_item2 Schema'
    )
    TFT7_Senna: Any = Field(..., examples=[None], title='The TFT7_Senna Schema')
    TFT7_Senna_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Senna_item0 Schema'
    )
    TFT7_Senna_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Senna_item1 Schema'
    )
    TFT7_Senna_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Senna_item2 Schema'
    )
    TFT7_Sett: Any = Field(..., examples=[None], title='The TFT7_Sett Schema')
    TFT7_Sett_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Sett_item0 Schema'
    )
    TFT7_Sett_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Sett_item1 Schema'
    )
    TFT7_Sett_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Sett_item2 Schema'
    )
    TFT7_Shen: Any = Field(..., examples=[None], title='The TFT7_Shen Schema')
    TFT7_Shen_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Shen_item0 Schema'
    )
    TFT7_Shen_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Shen_item1 Schema'
    )
    TFT7_Shen_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Shen_item2 Schema'
    )
    TFT7_Shyvana: Any = Field(..., examples=[None], title='The TFT7_Shyvana Schema')
    TFT7_Shyvana_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Shyvana_item0 Schema'
    )
    TFT7_Shyvana_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Shyvana_item1 Schema'
    )
    TFT7_Shyvana_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Shyvana_item2 Schema'
    )
    TFT7_Skarner: Any = Field(..., examples=[None], title='The TFT7_Skarner Schema')
    TFT7_Skarner_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Skarner_item0 Schema'
    )
    TFT7_Skarner_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Skarner_item1 Schema'
    )
    TFT7_Skarner_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Skarner_item2 Schema'
    )
    TFT7_Sona: Any = Field(..., examples=[None], title='The TFT7_Sona Schema')
    TFT7_Sona_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Sona_item0 Schema'
    )
    TFT7_Sona_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Sona_item1 Schema'
    )
    TFT7_Sona_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Sona_item2 Schema'
    )
    TFT7_Soraka: Any = Field(..., examples=[None], title='The TFT7_Soraka Schema')
    TFT7_Soraka_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Soraka_item0 Schema'
    )
    TFT7_Soraka_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Soraka_item1 Schema'
    )
    TFT7_Soraka_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Soraka_item2 Schema'
    )
    TFT7_Swain: Any = Field(..., examples=[None], title='The TFT7_Swain Schema')
    TFT7_Swain_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Swain_item0 Schema'
    )
    TFT7_Swain_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Swain_item1 Schema'
    )
    TFT7_Swain_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Swain_item2 Schema'
    )
    TFT7_Sylas: float = Field(..., examples=[2.0], title='The TFT7_Sylas Schema')
    TFT7_Sylas_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Sylas_item0 Schema'
    )
    TFT7_Sylas_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Sylas_item1 Schema'
    )
    TFT7_Sylas_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Sylas_item2 Schema'
    )
    TFT7_TahmKench: Any = Field(..., examples=[None], title='The TFT7_TahmKench Schema')
    TFT7_TahmKench_item0: Any = Field(
        ..., examples=[None], title='The TFT7_TahmKench_item0 Schema'
    )
    TFT7_TahmKench_item1: Any = Field(
        ..., examples=[None], title='The TFT7_TahmKench_item1 Schema'
    )
    TFT7_TahmKench_item2: Any = Field(
        ..., examples=[None], title='The TFT7_TahmKench_item2 Schema'
    )
    TFT7_Talon: float = Field(..., examples=[2.0], title='The TFT7_Talon Schema')
    TFT7_Talon_item0: str = Field(
        ..., examples=['ThiefsGloves'], title='The TFT7_Talon_item0 Schema'
    )
    TFT7_Talon_item1: str = Field(
        ..., examples=['FrozenHeart'], title='The TFT7_Talon_item1 Schema'
    )
    TFT7_Talon_item2: str = Field(
        ..., examples=['GuardianAngel'], title='The TFT7_Talon_item2 Schema'
    )
    TFT7_Taric: Any = Field(..., examples=[None], title='The TFT7_Taric Schema')
    TFT7_Taric_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Taric_item0 Schema'
    )
    TFT7_Taric_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Taric_item1 Schema'
    )
    TFT7_Taric_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Taric_item2 Schema'
    )
    TFT7_Thresh: Any = Field(..., examples=[None], title='The TFT7_Thresh Schema')
    TFT7_Thresh_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Thresh_item0 Schema'
    )
    TFT7_Thresh_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Thresh_item1 Schema'
    )
    TFT7_Thresh_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Thresh_item2 Schema'
    )
    TFT7_TrainerDragon: Any = Field(
        ..., examples=[None], title='The TFT7_TrainerDragon Schema'
    )
    TFT7_TrainerDragon_item0: Any = Field(
        ..., examples=[None], title='The TFT7_TrainerDragon_item0 Schema'
    )
    TFT7_TrainerDragon_item1: str = Field(
        ..., examples=['None'], title='The TFT7_TrainerDragon_item1 Schema'
    )
    TFT7_TrainerDragon_item2: str = Field(
        ..., examples=['None'], title='The TFT7_TrainerDragon_item2 Schema'
    )
    TFT7_Tristana: Any = Field(..., examples=[None], title='The TFT7_Tristana Schema')
    TFT7_Tristana_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Tristana_item0 Schema'
    )
    TFT7_Tristana_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Tristana_item1 Schema'
    )
    TFT7_Tristana_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Tristana_item2 Schema'
    )
    TFT7_Twitch: Any = Field(..., examples=[None], title='The TFT7_Twitch Schema')
    TFT7_Twitch_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Twitch_item0 Schema'
    )
    TFT7_Twitch_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Twitch_item1 Schema'
    )
    TFT7_Twitch_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Twitch_item2 Schema'
    )
    TFT7_Varus: Any = Field(..., examples=[None], title='The TFT7_Varus Schema')
    TFT7_Varus_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Varus_item0 Schema'
    )
    TFT7_Varus_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Varus_item1 Schema'
    )
    TFT7_Varus_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Varus_item2 Schema'
    )
    TFT7_Vladimir: Any = Field(..., examples=[None], title='The TFT7_Vladimir Schema')
    TFT7_Vladimir_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Vladimir_item0 Schema'
    )
    TFT7_Vladimir_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Vladimir_item1 Schema'
    )
    TFT7_Vladimir_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Vladimir_item2 Schema'
    )
    TFT7_Volibear: Any = Field(..., examples=[None], title='The TFT7_Volibear Schema')
    TFT7_Volibear_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Volibear_item0 Schema'
    )
    TFT7_Volibear_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Volibear_item1 Schema'
    )
    TFT7_Volibear_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Volibear_item2 Schema'
    )
    TFT7_Xayah: Any = Field(..., examples=[None], title='The TFT7_Xayah Schema')
    TFT7_Xayah_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Xayah_item0 Schema'
    )
    TFT7_Xayah_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Xayah_item1 Schema'
    )
    TFT7_Xayah_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Xayah_item2 Schema'
    )
    TFT7_Yasuo: Any = Field(..., examples=[None], title='The TFT7_Yasuo Schema')
    TFT7_Yasuo_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Yasuo_item0 Schema'
    )
    TFT7_Yasuo_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Yasuo_item1 Schema'
    )
    TFT7_Yasuo_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Yasuo_item2 Schema'
    )
    TFT7_Yone: Any = Field(..., examples=[None], title='The TFT7_Yone Schema')
    TFT7_Yone_item0: Any = Field(
        ..., examples=[None], title='The TFT7_Yone_item0 Schema'
    )
    TFT7_Yone_item1: Any = Field(
        ..., examples=[None], title='The TFT7_Yone_item1 Schema'
    )
    TFT7_Yone_item2: Any = Field(
        ..., examples=[None], title='The TFT7_Yone_item2 Schema'
    )
    TFT7_Zoe: Any = Field(..., examples=[None], title='The TFT7_Zoe Schema')
    TFT7_Zoe_item0: Any = Field(..., examples=[None], title='The TFT7_Zoe_item0 Schema')
    TFT7_Zoe_item1: Any = Field(..., examples=[None], title='The TFT7_Zoe_item1 Schema')
    TFT7_Zoe_item2: Any = Field(..., examples=[None], title='The TFT7_Zoe_item2 Schema')
    _id: str = Field(
        ...,
        examples=[
            'NA1_4387530978-wgvrKfcuCGDmgyrUmiXknS41acg6Y26hfQwsXNj_eJ86Tv8_Bb7SBOUVSQqI1JdyBSmq92XGDrGYHA'
        ],
        title='The _id Schema',
    )
